config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :notifications do
    get :showU, on: :member
  end
  resources :events
  resources :conferences do
    get :map, on: :collection
  end
  resources :timetables do
    get :show_image, on: :member
    get :timetable, on: :collection
  end
  resources :users do
    collection {post :import}
    get :import, on: :collection
    get :indexU, on: :collection
    get :editU, on: :collection
    get :badge, on: :collection
    get :account, on: :collection
    get :notificationsU, on: :collection
    get :badgeA, on: :collection
    get :coa, on: :collection
    get :changepw, on: :collection
  end
  resources :scans do
    get :qrU, on: :collection
    collection {post :validate_scan}
  end
  resources :bookings do
    member do
      put :request_certificate
      put :cancel_certificate
    end
    get :existing, on: :collection

  end
  resources :pages do
    get :home, on: :collection
  end


  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  get 'scans/index'
  post "scans/index" => "scans#validate_scan"

  root to: "bookings#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/timetables_controller.rb
#Timetables_controller is a ruby controller used to store functions for use throughout the application specific to Timetables tasks

class TimetablesController < ApplicationController
  before_action :set_timetable, only: [:show, :edit, :update, :destroy]

  # GET /timetables
  #Allows admins to see a list of timetables
  def index
    if current_user.access == 2
      redirect_to "/timetables/timetable"
    end
    @timetables = Timetable.all
  end

  # GET /timetables/1
  #Allows admins to see a specific timetable
  def show
  end

  # GET /timetables/new
  #Allows admins to create a new timetables
  def new
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
    @timetable = Timetable.new
    puts @timetable.to_json
  end

  # GET /timetables/1/edit
  #Allows admins to edit a specific timetables
  def edit
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
  end

  # POST /timetables
  #Allows methods in other files to create new timetables
  def create
    @timetable = Timetable.new(timetable_params)
    if @timetable.save
      redirect_to @timetable, notice: 'Timetable was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /timetables/1
  #Updates timetables with the current parameters when called -- used with forms
  def update
    if @timetable.update(timetable_params)
      redirect_to @timetable, notice: 'Timetable was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /timetables/1
  #Allows destruction of timetables
  def destroy
    @timetable.destroy
    redirect_to timetables_url, notice: 'Timetable was successfully destroyed.'
  end

  # GET /timetables/1
  #Show timetable image
  def show_image
    @timetable = Timetable.find(params[:id])
    if !@timetable.nil?
      send_file @timetable.timetable_image_file.url, disposition: 'inline'
    else
      redirect_to root_url, notice: "Timetable does not exist yet"
    end
  end

  def timetable
    if current_user.access == 1
      redirect_to "/timetables"
    end
    @bookings = Booking.where(user_id: current_user.id)
    @timetables = Array.new
    @bookings.each do |b|
      @timetable = Timetable.where(conference_id: b.conference_id).order(:id).last
      puts @timetable.as_json
      # if !@timetable.nil?
      #   send_file @timetable.timetable_image_file.url, disposition: 'inline'
      # else
      #   redirect_to root_url, notice: "Timetable does not exist yet"
      # end
      if !@timetable.nil?
        @timetables << @timetable
      end
    end
    @timetables = @timetables.uniq
    @names = Hash.new
    @timetables.each do |t|
      @name = Conference.where(id: t.conference_id).first
      @names1 = {t.conference_id => @name.name}
      @names.merge!(@names1)
    end
    # @timetable = Timetable.last!
    # puts @timetable.timetable_image_file.current_path
    # # if !@timetable.nil?
    # #   send_file @timetable.timetable_image_file.url, disposition: 'inline'
    # if @timetable.nil?
    #   redirect_to '/users/indexU', notice: "Timetable does not exist yet"
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      @timetable = Timetable.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def timetable_params
      params.require(:timetable).permit(:timetable_image_file, :timetable_image_file_cache, :conference_id)
    end
end

app/helpers/timetables_helper.rb
#Timetables_helper is a ruby helper used to extract complex logic out of the view in order to organize Timetables code better.
module TimetablesHelper
end

app/views/timetables/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@timetable) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :timetable_image_file, as: :file
    = f.hidden_field :timetable_image_file_cache
    = f.association :conference, prompt: "Select a Conference"


  .form-actions
    = f.button :submit, 'Upload Timetable', :class => 'btn btn-primary'

app/views/timetables/edit.html.haml
%h1 Editing Timetable

= render 'form'
%br
= link_to 'Show', @timetable, :class => 'btn btn-default'
\|
= link_to 'Back', timetables_path, :class => 'btn btn-default'

app/views/timetables/index.html.haml
%h1 Listing Timetable

.table-responsive
%table.table.table-striped
  %thead
    %tr
      %th Image Name
      %th Conference

  %tbody
    - @timetables.each do |timetable|
      %tr
        %td= timetable.timetable_image_file
        %td= timetable.conference_id
        %td.dropdown
          %btn.btn.btn-secondary.dropdown-toggle
            Options
          .dropdown-content
            = link_to 'Show', timetable
            = link_to 'Edit', edit_timetable_path(timetable)
            = link_to 'Destroy', timetable, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Timetable', new_timetable_path, :class => 'btn btn-primary'

app/views/timetables/new.html.haml
%h1 New Session

= render 'form'
%br
=link_to 'Back',timetables_path, :class => 'btn btn-default'

app/views/timetables/show.html.haml
%p#notice= notice
= image_tag show_image_timetable_path(@timetable), id: 'timetable', class: 'img-responsive', style: 'width:100%; height:auto;'

%br
= link_to 'Back', timetables_path, :class => 'btn btn-default'

app/views/timetables/timetable.html.haml
-# %img{src: show_image_timetable_path(@timetable), class: "img-responsive"}
%h1 My Timetables

.table-responsive
%table.table.table-striped
  %thead
    %tr
      %th Conference

  %tbody
    - @timetables.each do |timetable|
      %tr
        %td= @names[timetable.conference_id]
        %td= link_to 'Show', timetable, :class => 'btn btn-default'
%br