config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :notifications do
    get :showU, on: :member
  end
  resources :events
  resources :conferences do
    get :map, on: :collection
  end
  resources :timetables do
    get :show_image, on: :member
    get :timetable, on: :collection
  end
  resources :users do
    collection {post :import}
    get :import, on: :collection
    get :indexU, on: :collection
    get :editU, on: :collection
    get :badge, on: :collection
    get :account, on: :collection
    get :notificationsU, on: :collection
    get :badgeA, on: :collection
    get :coa, on: :collection
    get :changepw, on: :collection
  end
  resources :scans do
    get :qrU, on: :collection
    collection {post :validate_scan}
  end
  resources :bookings do
    member do
      put :request_certificate
      put :cancel_certificate
    end
    get :existing, on: :collection

  end
  resources :pages do
    get :home, on: :collection
  end


  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  get 'scans/index'
  post "scans/index" => "scans#validate_scan"

  root to: "bookings#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :bigint(8)        not null, primary key
#  not_des    :string
#  time       :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  not_id     :string
#

class Notification < ApplicationRecord
  validates :not_id, :not_des, presence: true
end

app/controllers/notifications_controller.rb
#Notifications_controller is a ruby controller used to store functions for use throughout the application specific to Notifications tasks

class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  #Allows admins to see a list of notifications
  def index
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
    @q = Notification.ransack(params[:q])
    @notifications = @q.result

  end

  # GET /notifications/1
  #Allows admins to see a specific notification
  def show
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
  end

  def showU
    if current_user.access == 1
      redirect_to notifications_url
    end
    @notification = Notification.where(id: params[:id]).first
    puts @notification.as_json
  end

  # GET /notifications/new
  #Allows admins to create a new notifications
  def new
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  #Allows admins to edit a specific notifications
  def edit
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
  end

  # POST /notifications
  #Allows methods in other files to create new notifications
  def create
    @notification = Notification.new(notification_params)
    @notification.time = Time.now.strftime("%d/%m/%Y %H:%M")

    if @notification.save
      redirect_to @notification, notice: 'Notification was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /notifications/1
  #Updates notifications with the current parameters when called -- used with forms
  def update
    if @notification.update(notification_params)
      redirect_to @notification, notice: 'Notification was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /notifications/1
  #Allows destruction of notifications
  def destroy
    @notification.destroy
    redirect_to notifications_url, notice: 'Notification was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def notification_params
      params.require(:notification).permit(:not_id, :not_des, :time)
    end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@notification) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :not_id, label: 'Notification Name', placeholder: "Enter Notification Title"
    = f.input :not_des, label: 'Notification Description', placeholder: "Enter Description"

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'

app/views/notifications/edit.html.haml
%h1 Editing notification

= render 'form'
%br
= link_to 'Show', @notification, :class => 'btn btn-default'
\|
= link_to 'Back', notifications_path, :class => 'btn btn-default'

app/views/notifications/index.html.haml
%h1 Notifications

= link_to 'New Notification', new_notification_path, class: 'btn btn-primary btn-new-notification'
%br
%br
= search_form_for @q do |f|
  -# filter name
  .form-row
    .col.form-group
      = f.search_field :not_id_cont, class: 'form-control', placeholder: 'Title Contains'
    .col.form-group
      .form-actions
        = f.submit "Search", class: 'btn btn-primary'
        = link_to 'Reset Search', notifications_url, :class => 'btn btn-default'


.table-responsive
%table.table.table-striped
  %thead
    %tr
      %th=sort_link(@q, :not_id, 'Title', default_order: :desc)
      %th=sort_link(@q, :time, 'Time')
      %th
      %th
      %th

  %tbody
    - @notifications.each do |notification|
      %tr
        %td= notification.not_id
        %td= notification.time
        %td.dropdown
          %btn.btn.btn-secondary.dropdown-toggle
            Options
          .dropdown-content
            = link_to 'Show', notification, class: 'dropdown-item'
            = link_to 'Edit', edit_notification_path(notification), class: 'dropdown-item'
            = link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item'

%br

app/views/notifications/new.html.haml
%h1 New notification

= render 'form'
%br
= link_to 'Back', notifications_path, :class => 'btn btn-default'

app/views/notifications/show.html.haml
%p#notice= notice

%p
  %b Notification Name:
  = @notification.not_id
%p
  %b Notification Description:
  = @notification.not_des
%p
  %b Time of Notification:
  = @notification.time

= link_to 'Edit', edit_notification_path(@notification), :class => 'btn btn-default'
\|
= link_to 'Back', notifications_path, :class => 'btn btn-default'

app/views/notifications/showU.html.haml
%p#notice= notice

%p
  %b Notification Name:
  = @notification.not_id
%p
  %b Notification Description:
  = @notification.not_des
%p
  %b Time of Notification:
  = @notification.time

= link_to 'Back', notificationsU_users_path, :class => 'btn btn-default'