config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :notifications do
    get :showU, on: :member
  end
  resources :events
  resources :conferences do
    get :map, on: :collection
  end
  resources :timetables do
    get :show_image, on: :member
    get :timetable, on: :collection
  end
  resources :users do
    collection {post :import}
    get :import, on: :collection
    get :indexU, on: :collection
    get :editU, on: :collection
    get :badge, on: :collection
    get :account, on: :collection
    get :notificationsU, on: :collection
    get :badgeA, on: :collection
    get :coa, on: :collection
    get :changepw, on: :collection
  end
  resources :scans do
    get :qrU, on: :collection
    collection {post :validate_scan}
  end
  resources :bookings do
    member do
      put :request_certificate
      put :cancel_certificate
    end
    get :existing, on: :collection

  end
  resources :pages do
    get :home, on: :collection
  end


  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  get 'scans/index'
  post "scans/index" => "scans#validate_scan"

  root to: "bookings#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id                :bigint(8)        not null, primary key
#  access_req        :text
#  attended          :boolean
#  booking_reference :string
#  catering          :boolean
#  certificate       :boolean          default(FALSE)
#  dietary_req       :string
#  institution       :string
#  ticket_type       :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  conference_id     :integer
#  user_id           :integer
#

class Booking < ApplicationRecord

  belongs_to :user
  belongs_to :conference

  validates_presence_of :user, :ticket_type
  validates :booking_reference, length: { is: 9 },numericality: { only_integer: true }, on: :create

end

app/controllers/bookings_controller.rb
#Bookings_controller is a ruby controller used to store functions for use throughout the application specific to Booking tasks

class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  #Allows admins to access all bookings
  def index
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
    @q = Booking.ransack(params[:q])
    @q.sorts = 'attended asc' if @q.sorts.empty?
    @bookings = @q.result
  end

  # GET /bookings/1
  #Allows admins to access specific bookings
  def show
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
  end

  def existing
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  #Allows admins to edit specific bookings
  def edit
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
    @count = Conference.where(id: @booking.conference_id).uniq.pluck(:days).first
    # (1..@count).each do
    puts @count
  end

  #Toggles the field in the database and sets it to true
  def request_certificate
    @booking = Booking.where(user_id: current_user.id).first
    if @booking.certificate == false
      @booking.toggle!(:certificate)
      redirect_to account_users_path, flash: {notice: "Successfully requested certificate!"}
    end
  end

  #Toggles the field in the database and sets it to false
  def cancel_certificate
    @booking = Booking.where(user_id: current_user.id).first
    if @booking.certificate == true
      @booking.toggle!(:certificate)
      redirect_to account_users_path, flash: {notice: "Successfully cancelled request!"}
    end
  end

  # POST /bookings
  #Allows creation of new bookings
  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking, notice: 'Booking was successfully created.'
    else
      render :existing
    end
  end

  # PATCH/PUT /bookings/1
  #Updates bookings with the current parameters when called -- used with forms
  def update
    if @booking.update(booking_params)
      redirect_to bookings_url, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bookings/1
  #Allows destruction of bookings
  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def booking_params
      params.require(:booking).permit(:booking_reference, :institution, :ticket_type, :access_req, :catering, :certificate, :attended, :dietary_req, :conference_id, :user_id)
    end


end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@booking) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :institution, placeholder: "Enter Institution"
    = f.label "Number of Days"
    = f.select(:ticket_type, options_for_select((1..@count).each))
  %br
    = f.input :access_req, label: "Access Requirements (e.g. Wheelchair)", placeholder: "Leave blank if unrequired"
    = f.input :catering
    = f.input :certificate
    = f.input :attended
    = f.input :dietary_req, label: "Dietary Requirements (e.g. Vegan)", placeholder: "Leave blank if unrequired"
    = f.association :conference, prompt: "Select a Conference"
    = f.association :user, prompt: "Choose a User"

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'

app/views/bookings/_form0.html.haml
-# frozen_string_literal: true
= simple_form_for(@booking) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :booking_reference, placeholder: "E.g. 123456789"
    = f.input :institution, placeholder: "Enter Institution"
    = f.input :ticket_type, label: "Number of Days", placeholder: "Enter the Number of Days this ticket is valid for"
    = f.input :access_req, label: "Access Requirements (e.g. Wheelchair)", placeholder: "Leave blank if unrequired"
    = f.input :catering
    = f.input :certificate
    = f.input :attended
    = f.input :dietary_req, label: "Dietary Requirements (e.g. Vegan)", placeholder: "Leave blank if unrequired"
    = f.association :conference, prompt: "Select a Conference"
    = f.association :user, prompt: "Choose a User"

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'

app/views/bookings/edit.html.haml
%h1 Editing booking

= render 'form'
%br

= link_to 'Show', @booking, :class => 'btn btn-default'
\|
= link_to 'Back', bookings_path, :class => 'btn btn-default'

app/views/bookings/existing.html.haml
%h1 Existing User Booking

= render 'form0'

%br

= link_to 'Back', bookings_path, :class => 'btn btn-default'

app/views/bookings/index.html.haml
%h5 Listing bookings

= link_to 'New Booking', new_booking_path, class: 'btn btn-primary btn-new-user'
%br
= search_form_for(@q) do |f|
  .form-row
    .col.form-group
      -# filter name
      = f.search_field :user_username_cont, class: 'form-control', placeholder: 'Username contains:',id: 'Search_username'
    .col.form-group
      -# filter institution
      = f.search_field :booking_reference_cont, class: 'form-control', placeholder: 'Booking Ref contains:',id: 'Search_bref'
  .form-group
    -# filter attended
    = f.label :attended
    = select :q, :attended_true, [['Yes', 1], ['No', 0]], { include_blank: 'All', selected: params[:q] ? params[:q][:attended_true] : '' }
  .form-actions
    = f.submit "Search", class: 'btn btn-primary'
    = link_to 'Reset Search', bookings_url, :class => 'btn btn-default'

.table-responsive
%table.table.table-striped
  %thead
    %tr
      %th=sort_link(@q, :user_id, 'User')
      %th=sort_link(@q, :booking_reference, 'Booking Reference')
      %th=sort_link(@q, :institution, 'Institution')
      %th=sort_link(@q, :ticket_type, 'Ticket Type')
      %th=sort_link(@q, :access_req, 'Access Requirements')
      %th=sort_link(@q, :catering, 'Catering')
      %th=sort_link(@q, :certificate, 'Certificate')
      %th=sort_link(@q, :attended, 'Attended')
      %th=sort_link(@q, :dietary_req, 'Dietary Requirements')
      %th=sort_link(@q, :conference_id, 'Conference')
      %th

  %tbody
    - @bookings.each do |booking|
      -if !booking.user.nil?
        %tr
          %td= booking.user.username
          %td= booking.booking_reference
          %td= booking.institution
          %td= booking.ticket_type > 1 ? " #{booking.ticket_type} Days " : " #{booking.ticket_type} Day "
          %td= booking.access_req
          %td= bool_to_glyph(booking.catering)
          %td= bool_to_glyph(booking.certificate)
          %td= bool_to_glyph(booking.attended)
          %td= booking.dietary_req
          %td= booking.conference_id
          %td.dropdown
            %btn.btn.btn-secondary.dropdown-toggle
              Options
            .dropdown-content
              = link_to 'Show', booking, class: 'dropdown-item'
              = link_to 'Edit', edit_booking_path(booking), class: 'dropdown-item'
              = link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item'
              -# = link_to 'Toggle Attended', toggle_attended_booking_path(booking), method: :patch, remote: :true,  class: 'dropdown-item'
              = link_to 'Toggle Attended', booking_path(booking, booking: {attended: !booking.attended}), method: :put, class: 'dropdown-item'

app/views/bookings/new.html.haml
%h1 New booking

= link_to 'Create New User', new_user_path, :class => 'btn btn-primary'
%br
%br
= link_to 'Create Booking for user', existing_bookings_path, :class => 'btn btn-primary'
%br
%br
= link_to 'Back', bookings_path, :class => 'btn btn-default'

app/views/bookings/show.html.haml
%p#notice= notice

%p
  %b Booking reference:
  = @booking.booking_reference

%p
  %b Institution:
  = @booking.institution
%p
  %b Ticket type:
  = @booking.ticket_type > 1 ? " #{@booking.ticket_type} Days " : " #{@booking.ticket_type} Day "

-if @booking.access_req != ""
  %p
    %b Access requirements:
    = @booking.access_req
%p
  %b Catering:
  -if @booking.catering == true
    = "Yes"
  -else
    = "No"
%p
  %b Certificate:
  -if @booking.certificate == true
    = "Yes"
  -else
    = "No"
%p
  %b Attended:
  -if @booking.attended == true
    = "Yes"
  -else
    = "No"
%p
  %b Dietary requirements:
  -if @booking.dietary_req == "" || @booking.dietary_req.nil?
    = "None specified"
  -else
    = @booking.dietary_req
%p
  %b Conference:
  = @booking.conference.name
%p
  %b User:
  = @booking.user.username



= link_to 'Edit', edit_booking_path(@booking), :class => 'btn btn-default'
\|
= link_to 'Back', bookings_path, :class => 'btn btn-default'