config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :notifications do
    get :showU, on: :member
  end
  resources :events
  resources :conferences do
    get :map, on: :collection
  end
  resources :timetables do
    get :show_image, on: :member
    get :timetable, on: :collection
  end
  resources :users do
    collection {post :import}
    get :import, on: :collection
    get :indexU, on: :collection
    get :editU, on: :collection
    get :badge, on: :collection
    get :account, on: :collection
    get :notificationsU, on: :collection
    get :badgeA, on: :collection
    get :coa, on: :collection
    get :changepw, on: :collection
  end
  resources :scans do
    get :qrU, on: :collection
    collection {post :validate_scan}
  end
  resources :bookings do
    member do
      put :request_certificate
      put :cancel_certificate
    end
    get :existing, on: :collection

  end
  resources :pages do
    get :home, on: :collection
  end


  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  get 'scans/index'
  post "scans/index" => "scans#validate_scan"

  root to: "bookings#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  access                 :integer
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string
#  encrypted_password     :string           default(""), not null
#  institution            :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  manager                :boolean
#  name                   :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  temp_pw                :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  require 'csv'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :recoverable
  validates_format_of    :email,    :with  => Devise.email_regexp
  validates_length_of    :password, :within => Devise.password_length, on: :create
  validates_length_of    :password, :within => Devise.password_length, on: :changepw
  validates_length_of    :password, :within => Devise.password_length, on: :editAdmin
  validates_uniqueness_of    :username,     :case_sensitive => true
  has_many :booking
  validates :username, :password, :access, :email, :name, presence: true, on: :create
  validates :username, :password , :confirmation => true, :length =>{:within => 4..40}, on: :create
#  validates :username, :password , :confirmation => true, :length =>{:within => 6..40}
  validates_confirmation_of :password




  def self.UserGen(name, email)
    emailName = email.split("@").first
    @usrnm = emailName.to_s + name.first.to_s + name.last.to_s
    @usersomething = User.where("username ~* ?", @usrnm)
    if (@usersomething.length != 0)
      return @usrnm + @usersomething.length.to_s
    else
      return @usrnm
    end
  end


  def self.import(file)
    csv = CSV.read(file.path, headers: true, skip_blanks: true)
    CSV.foreach(file.path, headers: true, skip_blanks: true) do |b|
    csv_valid = (['Name','Organisation','Email','Dietary Requirements', 'Access Requirements', 'Catering', 'Number of Days', 'Online Store Ref/ITO'] - csv.headers.compact).empty?
    return false unless csv_valid

    new_user = User.new
    new_user.name = b["Name"]
    new_user.email = b["Email"]
    # hard coded username. this is where we need to generate it automatically.
    new_user.username = UserGen(b["Name"],b["Email"])
    new_user.access = 2
    # hard coded password. this is where we need to generate it automatically.
    pw = SecureRandom.hex(8)
    new_user.password = pw
    new_user.institution = b["Organisation"]
    new_user.temp_pw = pw
    new_user.save!


    new_booking = Booking.new
    new_booking.institution = b["Organisation"]
    new_booking.dietary_req = b["Dietary Requirements"]
    new_booking.access_req = b["Access Requirements"]
    new_booking.booking_reference = b["Online Store Ref/ITO"]
    new_booking.ticket_type = b["Number of Days"]
    catering = b["Catering"]
    if catering == "Yes" || catering == "yes"
      new_booking.catering = true
    else
      new_booking.catering = false
    end
    new_booking.attended = false
    new_booking.user_id = new_user.id
    # check Easter Week 2 for issue about conference ID pls.
    new_booking.conference_id = b["Conference ID"]
    new_booking.save!

    UserMailer.welcome_email(new_user).deliver
    end
    return true
  end


end

app/controllers/users_controller.rb
#Users_controller is a ruby controller used to store functions for use throughout the application specific to User tasks

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # helper_method :sort_column, :sort_direction

  # GET /users
  #Allows admins to see a list of users
  def index
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
    @q = User.ransack(params[:q])
    @q.sorts = 'name asc' if @q.sorts.empty?
    @users_with_attended = @q.result.left_outer_joins(:booking).distinct.select('users.*,bookings.attended AS bookings_attended, bookings.booking_reference AS bookings_reference')
    #PATCH/PUT toggle Attended
    # def toggle_attended
    #   @booking  =  Booking.where(user_id: @user.id)
    #   @booking.toggle!(:attended)
    # end
  end

  #  GET /indexU
  #Allows users to see their current booking
  def indexU
    if current_user.access == 1
        redirect_to "/users/"
    end
   @bookingUserID = Booking.where(user_id: current_user.id)
  end
  # end

  # GET /import
  #Allows importing of files in other methods
  def import
    file = params[:file]
    type = file.content_type.chars.last(3).join
    if type == "csv"
      User.import(params[:file])
      redirect_to "/users", notice: "Successfully Imported File!"
    else
      redirect_to "/users", notice: "Selected file was not of correct format (.csv)"
    end
  end

  # GET /notificationsU
  #Allows users to see all notifications created
  def notificationsU
    if current_user.access == 1
      redirect_to "/users"
    end
    @notifications = Notification.all
  end

  # GET /account
  #Allow users to see their account
  def account
    if current_user.access == 1
      redirect_to root_url
    end
    @booking = Booking.where(user_id: current_user.id)
  end

  # GET /editU
  #Allows users to edit their account details
  def editU
    @user = current_user
  end

  # GET /badge
  #Allow users to see their badge
  def badge
    @bookingUserID = Booking.where(user_id: current_user.id)
  end

  def changepw
    @user = current_user
  end
  # GET /users/1
  #Allow admins to see specific user accounts
  def show
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
  end

  # GET /users/new
  #Allow admins to create user accounts
  def new
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
    @user = User.new
  end

  # GET /users/1/edit
  #Allow admins to edit specific user accounts
  def edit
    if current_user.access == 2
      redirect_to "/users/indexU"
    end
    @booking  =  Booking.where(user_id: @user.id)
  end

  # POST /users
  #Allows the creation of new users by other methods
  def create
    @user = User.new(user_params)
    pw = SecureRandom.hex(8)
    @user.password = pw
    @user.temp_pw = pw
    if @user.save
      UserMailer.welcome_email(@user).deliver
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  #Updates users with the current parameters when called -- used with forms
  def update
    puts @user.access.as_json
    if current_user.access == 1 && @user.access == 2
      if @user.update(user_params)
        redirect_to '/users', notice: 'User was successfully updated.'
      else
        render :edit
      end
    elsif current_user.access == 1
      if @user.update(user_params)
        redirect_to '/users', notice: 'User was successfully updated.'
      else
        render :edit
      end
    else
      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to '/users/account', notice: 'User was successfully updated.'
      else
        render :editU
      end
    end
  end

  # DELETE /users/1
  #Allows destruction of users
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:userid, :username, :password, :access, :institution, :email, :name)
    end

    # Only allow a trusted parameter "white list" through.
    def notification_params
      params.require(:notification).permit(:not_id, :not_des, :time)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :username, placeholder: "Enter Username"
    = f.label "User Access"
    %br
    = f.select :access,[['Admin',1],['Delegate', 2]]
    = f.input :institution, placeholder: "Enter Institution"
    = f.input :email, placeholder: "Enter Email Address"
    = f.input :name, placeholder: "Enter Name"
    -# - @booking.each do |b|
    -#   = b.input :attended

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'

app/views/users/_form0.html.haml
-# frozen_string_literal: true
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.label "User Access"
    %br
    = f.select :access, [['Admin',1],['Delegate', 2]]
    = f.input :institution
    = f.input :email
    = f.input :name

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'

app/views/users/_form1.html.haml
-# frozen_string_literal: true
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :username
    = f.input :password
    = f.label "User Access"
    %br
    = f.select :access, [['Admin',1],['Delegate', 2]]
    = f.input :institution
    = f.input :email
    = f.input :name
    -# - @booking.each do |b|
    -#   = b.input :attended

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'

app/views/users/account.html.haml
%h1 Account
%p#notice= notice

%p
  %b Username:
  = current_user.username
%p
  %b Email:
  = current_user.email
%p
  %b Name:
  = current_user.name
%p
  %b Certificate of Attendance?
= link_to "Request", request_certificate_booking_path(@booking), method: :put, :class => "btn btn-default"
= link_to "Cancel Request", cancel_certificate_booking_path(@booking), method: :put, :class => "btn btn-default"

%br
%br
= link_to 'Edit Account', "/users/editU", :class => "btn btn-primary"
= link_to 'Change Password', "/users/changepw", :class => "btn btn-primary"

app/views/users/badge.html.haml
%h1 Badge

- @bookingUserID.each do |b|
  .card
    %p.days
      = b.ticket_type > 1 ? " #{b.ticket_type} Days " : " #{b.ticket_type} Day "
    %h1{style: 'margin: 0 auto'}
      = current_user.name
    %h3{style: 'margin: 10px auto 20px'}
      = current_user.institution

    %img{src: '/badge-temp.png', class: "card-img-responsive", id: "badge"}

%br

app/views/users/changepw.html.haml
%h1 Changing Password for #{@user.username}
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.label "New Password:"
    = f.password_field :password, hide_label: true, placeholder: "Enter a new Password" , id: 'new-password'
    %br
    = f.label "Confirm Password:"
    = f.password_field :password_confirmation, hide_label: true,
     placeholder: "Confirm new Password", id: 'confirm-password',
     :class => 'never-submit'

  %span#message
  %br
  .form-actions
    = f.button :submit, value: "Change Password", :id => 'submit-password', :disabled => "disabled"

:javascript
  $(document).ready(function() {
    $('form').submit(function() {
      $('.never-submit').prop('disabled', true);
      return true;
    });
  });

  $('#new-password, #confirm-password').on('keyup', function() {
    if ($('#new-password').val().length > 5) {
      $('#message').hide();
      if ($('#new-password').val() === $('#confirm-password').val()) {
        $('#message').show();
        $('#message').html('Matching').css('color', 'green');
        $('#submit-password').prop('disabled', false);
      } else {
        $('#message').show();
        $('#message').html('Passwords do not match').css('color', 'red');
        $('#submit-password').prop('disabled', true);
      }
    } else {
      $('#message').html('Password must be 6 or more characters long').css('color', 'red');
    }
  });

app/views/users/edit.html.haml
%h1 Editing user: #{@user.username}

- if @user.access == 2
  = render 'form0'
- else
  = render 'form1'
%br
= link_to 'Show', @user, :class => "btn btn-default"
\|
= link_to 'Back', users_path, :class => "btn btn-default"

app/views/users/editU.html.haml
%h1 Editing user #{@user.username}

= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :username
    = f.input :institution
    = f.input :email
    = f.input :name


  .form-actions
    = f.button :submit, :class => "btn btn-primary"

app/views/users/index.html.haml
%br
%h2 All users

= link_to 'New User', new_user_path, class: 'btn btn-primary btn-new-user'
= form_tag import_users_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import", class: 'btn btn-secondary'
%br

= search_form_for(@q) do |f|
  .form-row
    .col.form-group
      -# filter name
      -# = f.label :name_cont
      = f.search_field :name_cont, class: 'form-control', placeholder: 'Name Contains:', id: 'S-name'
    .col.form-group
      -# filter institution
      = f.search_field :institution_cont, class: 'form-control', placeholder: 'Institution Contains: ', id: 'S-institution'
  .form-group
    -# filter attended
    = f.label :attended
    = select :q, :booking_attended_true, [['Yes', 1], ['No', 0]], { include_blank: 'All', selected: params[:q] ? params[:q][:booking_attended_true] : '' }
  .form-actions
    = f.submit "Search", class: 'btn btn-primary'
    = link_to 'Reset Search', users_path, :class => "btn btn-default"

%br
.table-responsive
%table.table.table-striped#userstable
  %thead
    %tr
      %th=sort_link(@q, :username, 'Username')
      %th=sort_link(@q, :access, 'Access')
      %th=sort_link(@q, :institution, 'Institution')
      %th=sort_link(@q, :email, 'Email')
      %th=sort_link(@q, :name, 'Name', default_order: :desc)
      %th Attended
      %th
  %tbody
    - @users_with_attended.each do |user|
      %tr
        %td= user.username
        -if user.access == 1
          %td= "Admin"
        -else
          %td= "Delegate"
        %td= user.institution
        %td= user.email
        %td= user.name
        %td= bool_to_glyph(user.bookings_attended)
        %td.dropdown
          %btn.btn.btn-secondary.dropdown-toggle
            Options
          .dropdown-content
            = link_to 'Show', user, class: 'dropdown-item'
            = link_to 'Edit', edit_user_path(user), class: 'dropdown-item'
            = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item'
            -# = link_to 'Toggle Attended', toggle_attended_booking_path(Booking.where(user_id: user.id).first), method: :patch, remote: :true,  class: 'dropdown-item', :onclick => 'location.reload()'
            -# = link_to 'Toggle Attended', edit_booking_path(Booking.where(user_id: user.id).first), class: 'dropdown-item'

app/views/users/indexU.html.haml
%h1 Homepage

%b Welcome
= current_user.name
%h3 QR codes

- @bookingUserID.each do |b|
 %b Conference:
 - Conference.where(id: b.conference_id).each do |c|
  = c.name
  %br
 %img{src: generate_qr(b.booking_reference), class: "qr-code"}
 %br
%br


%b To subscribe to our new mailing list and to stay up to date with the conference, please
%a{:href => "https://uksemiconductors.us12.list-manage.com/subscribe?u=28a002a1a3ef6e637c55b6b97&id=0d9a6c398d"}click here.

app/views/users/new.html.haml
%h1 Add new participants

= render 'form'
%br
= link_to 'Back', users_path, :class => "btn btn-default"

app/views/users/notificationsU.html.haml
%h3 Notifications
.table-responsive
%table.table.table-striped
  %thead
    %tr
      %th Notification Name
      %th Time
      %th
      %th
      %th

  %tbody
    - @notifications.each do |notification|
      %tr
        %td= notification.not_id
        %td= notification.time
        %td= link_to 'Show', showU_notification_path(notification), :class => 'btn btn-default'

%br

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Username:
  = @user.username
%p
  %b Access:
  -if @user.access == 1
    = "Admin"
  -else
    = "Delegate"
%p
  %b Institution:
  = @user.institution
%p
  %b Email:
  = @user.email


= link_to 'Edit', edit_user_path(@user), :class => "btn btn-default"
\|
= link_to 'Back', users_path, :class => "btn btn-default"